-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.alkash
(
    alkash_id serial NOT NULL,
    alkash_name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    alkash_surname character varying(30) COLLATE pg_catalog."default" NOT NULL,
    alkash_email character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT alkash_pkey PRIMARY KEY (alkash_id)
);

CREATE TABLE IF NOT EXISTS public.drink
(
    drink_id serial NOT NULL,
    drink_manufacturer character varying(30) COLLATE pg_catalog."default" NOT NULL,
    drink_cost integer NOT NULL,
    foreign_key_manufacturer_id integer NOT NULL,
    foreign_key_store_id integer,
    CONSTRAINT drink_pkey PRIMARY KEY (drink_id)
);

CREATE TABLE IF NOT EXISTS public.manufacturer
(
    manufacturer_id serial NOT NULL,
    manufacturer_name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    manufacturer_address text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT manufacturer_pkey PRIMARY KEY (manufacturer_id)
);

CREATE TABLE IF NOT EXISTS public.store
(
    store_id serial NOT NULL,
    store_address text COLLATE pg_catalog."default" NOT NULL,
    store_rating double precision NOT NULL,
    CONSTRAINT store_pkey PRIMARY KEY (store_id)
);

ALTER TABLE IF EXISTS public.drink
    ADD CONSTRAINT drink_foreign_key_manufacturer_id_fkey FOREIGN KEY (foreign_key_manufacturer_id)
    REFERENCES public.manufacturer (manufacturer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.drink
    ADD CONSTRAINT foreign_key_store FOREIGN KEY (foreign_key_store_id)
    REFERENCES public.store (store_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;